// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHFlbHXjQoY6r8Bj_t8HCl4TPPFVPrILE',
    appId: '1:144881323685:web:f2f8496ac54a52ceaf074c',
    messagingSenderId: '144881323685',
    projectId: 'auth-ca1d9',
    authDomain: 'auth-ca1d9.firebaseapp.com',
    storageBucket: 'auth-ca1d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hJLXyPNccyI6mP20utJR7jaNjPGMIkU',
    appId: '1:144881323685:android:a094c6e61b7bf0c1af074c',
    messagingSenderId: '144881323685',
    projectId: 'auth-ca1d9',
    storageBucket: 'auth-ca1d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfBfutce4ws66e3HQHony6ldg98_wM6U',
    appId: '1:144881323685:ios:c480b56eb2b8d1afaf074c',
    messagingSenderId: '144881323685',
    projectId: 'auth-ca1d9',
    storageBucket: 'auth-ca1d9.firebasestorage.app',
    iosBundleId: 'com.example.hotline_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfBfutce4ws66e3HQHony6ldg98_wM6U',
    appId: '1:144881323685:ios:c480b56eb2b8d1afaf074c',
    messagingSenderId: '144881323685',
    projectId: 'auth-ca1d9',
    storageBucket: 'auth-ca1d9.firebasestorage.app',
    iosBundleId: 'com.example.hotline_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHFlbHXjQoY6r8Bj_t8HCl4TPPFVPrILE',
    appId: '1:144881323685:web:f8010c113fccfb20af074c',
    messagingSenderId: '144881323685',
    projectId: 'auth-ca1d9',
    authDomain: 'auth-ca1d9.firebaseapp.com',
    storageBucket: 'auth-ca1d9.firebasestorage.app',
  );
}
